config/routes.rb
Rails.application.routes.draw do
  get 'client/index'
  get 'admin/index'

  resources :benefits
  resources :emp_details

  devise_for :users, controllers: {
    registrations: 'users/registrations' # Use the full namespace here
  }

  devise_scope :user do
    authenticated :user do
      root 'admin#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/benefit.rb
class Benefit < ApplicationRecord
end

app/controllers/benefits_controller.rb
class BenefitsController < ApplicationController
  before_action :set_benefit, only: %i[ show edit update destroy ]

  # GET /benefits or /benefits.json
  def index
    @benefits = Benefit.all
  end

  # GET /benefits/1 or /benefits/1.json
  def show
  end

  # GET /benefits/new
  def new
    @benefit = Benefit.new
  end

  # GET /benefits/1/edit
  def edit
  end

  # POST /benefits or /benefits.json
  def create
    @benefit = Benefit.new(benefit_params)

    respond_to do |format|
      if @benefit.save
        format.html { redirect_to benefit_url(@benefit), notice: "Benefit was successfully created." }
        format.json { render :show, status: :created, location: @benefit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @benefit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /benefits/1 or /benefits/1.json
  def update
    respond_to do |format|
      if @benefit.update(benefit_params)
        format.html { redirect_to benefit_url(@benefit), notice: "Benefit was successfully updated." }
        format.json { render :show, status: :ok, location: @benefit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @benefit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /benefits/1 or /benefits/1.json
  def destroy
    @benefit.destroy

    respond_to do |format|
      format.html { redirect_to benefits_url, notice: "Benefit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_benefit
      @benefit = Benefit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def benefit_params
      params.require(:benefit).permit(:benefit)
    end
end

app/helpers/benefits_helper.rb
module BenefitsHelper
end

app/views/benefits/_benefit.html.erb
<div id="<%= dom_id benefit %>">
  <p>
    <strong>Benefit:</strong>
    <%= benefit.benefit %>
  </p>

</div>

app/views/benefits/_form.html.erb
<%= simple_form_for(@benefit) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :benefit %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/benefits/edit.html.erb
<div class="card">
  <h5 class="card-header">Edit benefit</h5>
  <div class="card-body">
    <%= render "form", benefit: @benefit %>
  </div>
</div>

app/views/benefits/index.html.erb
<%= content_tag :h1, "List of Benefits" %>


<div class="text-end mb-3">
  <%= link_to new_benefit_path, class: 'btn btn-primary' do %>
    New Benefit
  <% end %>
</div>


  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
      <th>#</th>
            <th>Benefit</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
      <% @benefits.each do |benefit| %>
        <tr>

        <th scope="row"><%= benefit.id %></th>
        <td><%= benefit.benefit %></td>
    
          <td>
            <%= link_to 'View', benefit, class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_benefit_path(benefit), class: 'btn btn-secondary btn-sm' %>
            <%= link_to "Delete", benefit, class: "btn btn-danger btn-sm", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>

app/views/benefits/new.html.erb
<div class="card">
  <h5 class="card-header">New benefit</h5>
  <div class="card-body">
    <%= render "form", benefit: @benefit %>
  </div>
</div>

app/views/benefits/show.html.erb
<%= render @benefit %>

<div>
  <%= link_to "Edit", edit_benefit_path(@benefit), class: 'btn btn-primary' %> |
  <%= link_to "Back", benefits_path, class: 'btn btn-primary' %>

  <%= button_to "Delete", @benefit, method: :delete, class: 'btn btn-danger' %>
</div>