config/routes.rb
Rails.application.routes.draw do
  get 'client/index'
  get 'admin/index'

  resources :benefits
  resources :emp_details

  devise_for :users, controllers: {
    registrations: 'users/registrations' # Use the full namespace here
  }

  devise_scope :user do
    authenticated :user do
      root 'admin#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/emp_detail.rb
class EmpDetail < ApplicationRecord
end

app/controllers/emp_details_controller.rb
class EmpDetailsController < ApplicationController
  before_action :set_emp_detail, only: %i[ show edit update destroy ]

  # GET /emp_details or /emp_details.json
  def index
    @emp_details = EmpDetail.all
  end

  # GET /emp_details/1 or /emp_details/1.json
  def show
  end

  # GET /emp_details/new
  def new
    @emp_detail = EmpDetail.new
  end

  # GET /emp_details/1/edit
  def edit
  end

  # POST /emp_details or /emp_details.json
  def create
    @emp_detail = EmpDetail.new(emp_detail_params)

    respond_to do |format|
      if @emp_detail.save
        format.html { redirect_to emp_detail_url(@emp_detail), notice: "Emp detail was successfully created." }
        format.json { render :show, status: :created, location: @emp_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @emp_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emp_details/1 or /emp_details/1.json
  def update
    respond_to do |format|
      if @emp_detail.update(emp_detail_params)
        format.html { redirect_to emp_detail_url(@emp_detail), notice: "Emp detail was successfully updated." }
        format.json { render :show, status: :ok, location: @emp_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @emp_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emp_details/1 or /emp_details/1.json
  def destroy
    @emp_detail.destroy

    respond_to do |format|
      format.html { redirect_to emp_details_url, notice: "Emp detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emp_detail
      @emp_detail = EmpDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def emp_detail_params
      params.require(:emp_detail).permit(:fullname, :emp_id, :rank, :division, :sup_name, :pos_title, :ser_year, :ser_month, :educ_course, :educ_grad, :educ_skill, :educ_certificate, :educ_othskill, :contact, :department, :sup_title, :hr_perday, :hr_perweek, :break, :launch, :ot_weekday, :ot_weekend, :workday)
    end
end

app/helpers/emp_details_helper.rb
module EmpDetailsHelper
end

app/views/emp_details/_emp_detail.html.erb
<div id="<%= dom_id emp_detail %>">
  <p>
    <strong>Fullname:</strong>
    <%= emp_detail.fullname %>
  </p>

  <p>
    <strong>Emp:</strong>
    <%= emp_detail.emp_id %>
  </p>

  <p>
    <strong>Rank:</strong>
    <%= emp_detail.rank %>
  </p>

  <p>
    <strong>Division:</strong>
    <%= emp_detail.division %>
  </p>

  <p>
    <strong>Sup name:</strong>
    <%= emp_detail.sup_name %>
  </p>

  <p>
    <strong>Pos title:</strong>
    <%= emp_detail.pos_title %>
  </p>

  <p>
    <strong>Ser year:</strong>
    <%= emp_detail.ser_year %>
  </p>

  <p>
    <strong>Ser month:</strong>
    <%= emp_detail.ser_month %>
  </p>

  <p>
    <strong>Educ course:</strong>
    <%= emp_detail.educ_course %>
  </p>

  <p>
    <strong>Educ grad:</strong>
    <%= emp_detail.educ_grad %>
  </p>

  <p>
    <strong>Educ skill:</strong>
    <%= emp_detail.educ_skill %>
  </p>

  <p>
    <strong>Educ certificate:</strong>
    <%= emp_detail.educ_certificate %>
  </p>

  <p>
    <strong>Educ othskill:</strong>
    <%= emp_detail.educ_othskill %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= emp_detail.contact %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= emp_detail.department %>
  </p>

  <p>
    <strong>Sup title:</strong>
    <%= emp_detail.sup_title %>
  </p>

  <p>
    <strong>Hr perday:</strong>
    <%= emp_detail.hr_perday %>
  </p>

  <p>
    <strong>Hr perweek:</strong>
    <%= emp_detail.hr_perweek %>
  </p>

  <p>
    <strong>Break:</strong>
    <%= emp_detail.break %>
  </p>

  <p>
    <strong>Launch:</strong>
    <%= emp_detail.launch %>
  </p>

  <p>
    <strong>Ot weekday:</strong>
    <%= emp_detail.ot_weekday %>
  </p>

  <p>
    <strong>Ot weekend:</strong>
    <%= emp_detail.ot_weekend %>
  </p>

  <p>
    <strong>Workday:</strong>
    <%= emp_detail.workday %>
  </p>

</div>

app/views/emp_details/_form.html.erb
<%= simple_form_for(@emp_detail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :fullname %>
    <%= f.input :emp_id %>
    <%= f.input :rank %>
    <%= f.input :division %>
    <%= f.input :sup_name %>
    <%= f.input :pos_title %>
    <%= f.input :ser_year %>
    <%= f.input :ser_month %>
    <%= f.input :educ_course %>
    <%= f.input :educ_grad %>
    <%= f.input :educ_skill %>
    <%= f.input :educ_certificate %>
    <%= f.input :educ_othskill %>
    <%= f.input :contact %>
    <%= f.input :department %>
    <%= f.input :sup_title %>
    <%= f.input :hr_perday %>
    <%= f.input :hr_perweek %>
    <%= f.input :break %>
    <%= f.input :launch %>
    <%= f.input :ot_weekday %>
    <%= f.input :ot_weekend %>
    <%= f.input :workday %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/emp_details/edit.html.erb
<div class="card">
  <h5 class="card-header">Edit emp detail</h5>
  <div class="card-body">
    <%= render "form", emp_detail: @emp_detail %>
  </div>
</div>

app/views/emp_details/index.html.erb
<%= content_tag :h1, "List of Emp Details" %>


<div class="text-end mb-3">
  <%= link_to new_emp_detail_path, class: 'btn btn-primary' do %>
    New Emp Detail
  <% end %>
</div>


  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
      <th>#</th>
            <th>Fullname</th>
            <th>Emp</th>
            <th>Rank</th>
            <th>Division</th>
            <th>Sup Name</th>
            <th>Pos Title</th>
            <th>Ser Year</th>
            <th>Ser Month</th>
            <th>Educ Course</th>
            <th>Educ Grad</th>
            <th>Educ Skill</th>
            <th>Educ Certificate</th>
            <th>Educ Othskill</th>
            <th>Contact</th>
            <th>Department</th>
            <th>Sup Title</th>
            <th>Hr Perday</th>
            <th>Hr Perweek</th>
            <th>Break</th>
            <th>Launch</th>
            <th>Ot Weekday</th>
            <th>Ot Weekend</th>
            <th>Workday</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
      <% @emp_details.each do |emp_detail| %>
        <tr>

        <th scope="row"><%= emp_detail.id %></th>
        <td><%= emp_detail.fullname %></td>
        <td><%= emp_detail.emp_id %></td>
        <td><%= emp_detail.rank %></td>
        <td><%= emp_detail.division %></td>
        <td><%= emp_detail.sup_name %></td>
        <td><%= emp_detail.pos_title %></td>
        <td><%= emp_detail.ser_year %></td>
        <td><%= emp_detail.ser_month %></td>
        <td><%= emp_detail.educ_course %></td>
        <td><%= emp_detail.educ_grad %></td>
        <td><%= emp_detail.educ_skill %></td>
        <td><%= emp_detail.educ_certificate %></td>
        <td><%= emp_detail.educ_othskill %></td>
        <td><%= emp_detail.contact %></td>
        <td><%= emp_detail.department %></td>
        <td><%= emp_detail.sup_title %></td>
        <td><%= emp_detail.hr_perday %></td>
        <td><%= emp_detail.hr_perweek %></td>
        <td><%= emp_detail.break %></td>
        <td><%= emp_detail.launch %></td>
        <td><%= emp_detail.ot_weekday %></td>
        <td><%= emp_detail.ot_weekend %></td>
        <td><%= emp_detail.workday %></td>
    
          <td>
            <%= link_to 'View', emp_detail, class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_emp_detail_path(emp_detail), class: 'btn btn-secondary btn-sm' %>
            <%= link_to "Delete", emp_detail, class: "btn btn-danger btn-sm", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>

app/views/emp_details/new.html.erb
<div class="card">
  <h5 class="card-header">New emp detail</h5>
  <div class="card-body">
    <%= render "form", emp_detail: @emp_detail %>
  </div>
</div>

app/views/emp_details/show.html.erb
<%= render @emp_detail %>

<div>
  <%= link_to "Edit", edit_emp_detail_path(@emp_detail), class: 'btn btn-primary' %> |
  <%= link_to "Back", emp_details_path, class: 'btn btn-primary' %>

  <%= button_to "Delete", @emp_detail, method: :delete, class: 'btn btn-danger' %>
</div>