config/routes.rb
Rails.application.routes.draw do
  get 'client/index'
  get 'admin/index'

  resources :benefits
  resources :emp_details

  devise_for :users, controllers: {
    registrations: 'users/registrations' # Use the full namespace here
  }

  devise_scope :user do
    authenticated :user do
      root 'admin#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
  <div class="container-fluid">
    <%= image_tag('logo.png', alt: 'Logo', style: 'height:80px; width:auto', class: 'navbar-logo') %>
    <a class="navbar-brand text-uppercase" href="#">1CISP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        <li class="text-uppercase">
          <%= link_to "Home", client_index_path, class: 'nav-link' if current_user&.admin? %>
        </li>
        <li class="text-uppercase">
          <%= link_to "Users", admin_index_path, class: 'nav-link' if current_user&.admin? %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link mx-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.email if user_signed_in? %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, class: 'dropdown-item', data: { turbo_method: :delete } %> 
            </li>
            <li>
              <%= link_to "Edit Profile", edit_user_registration_path, class: 'dropdown-item' %>
            </li>
            <li><a class="dropdown-item" href="#">Contact us</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrFinal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/png" href="<%= asset_path('logo.png') %>">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navbar'%>
 
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true" data-controller="modal"
      data-action="turbo:frame-load->modal#open" data-bs-focus="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= turbo_frame_tag "reg_form_modal" %>
      </div>
    </div>
  </div>

    <%= yield %>
    </div>
  </body>
</html>